Attaching to a433-microservices_item-db_1, a433-microservices_item-app_1
[33mitem-db_1   |[0m 2024-03-20T15:43:19.378+0000 I CONTROL  [initandlisten] MongoDB starting : pid=1 port=27017 dbpath=/data/db 64-bit host=83706562d882
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] db version v3.6.23
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] git version: d352e6a4764659e0d0350ce77279de3c1f243e5c
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] allocator: tcmalloc
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] modules: none
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] build environment:
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten]     distmod: ubuntu1604
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten]     distarch: x86_64
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten]     target_arch: x86_64
[33mitem-db_1   |[0m 2024-03-20T15:43:19.379+0000 I CONTROL  [initandlisten] options: { net: { bindIpAll: true } }
[33mitem-db_1   |[0m 2024-03-20T15:43:19.386+0000 I -        [initandlisten] Detected data files in /data/db created by the 'wiredTiger' storage engine, so setting the active storage engine to 'wiredTiger'.
[33mitem-db_1   |[0m 2024-03-20T15:43:19.386+0000 I STORAGE  [initandlisten] 
[33mitem-db_1   |[0m 2024-03-20T15:43:19.386+0000 I STORAGE  [initandlisten] ** WARNING: Using the XFS filesystem is strongly recommended with the WiredTiger storage engine
[33mitem-db_1   |[0m 2024-03-20T15:43:19.386+0000 I STORAGE  [initandlisten] **          See http://dochub.mongodb.org/core/prodnotes-filesystem
[33mitem-db_1   |[0m 2024-03-20T15:43:19.386+0000 I STORAGE  [initandlisten] wiredtiger_open config: create,cache_size=373M,cache_overflow=(file_max=0M),session_max=20000,eviction=(threads_min=4,threads_max=4),config_base=false,statistics=(fast),compatibility=(release="3.0",require_max="3.0"),log=(enabled=true,archive=true,path=journal,compressor=snappy),file_manager=(close_idle_time=100000),statistics_log=(wait=0),verbose=(recovery_progress),
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[36mitem-app_1  |[0m > node ./bin/www
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m NODE_ENV: production
[36mitem-app_1  |[0m /app/node_modules/mongodb/lib/mongo_client.js:421
[36mitem-app_1  |[0m           throw err
[36mitem-app_1  |[0m           ^
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m AssertionError [ERR_ASSERTION]: null == Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.19.0.2:27017
[36mitem-app_1  |[0m     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
[36mitem-app_1  |[0m   name: 'MongoError'
[36mitem-app_1  |[0m }]
[36mitem-app_1  |[0m     at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[36mitem-app_1  |[0m     at Pool.emit (events.js:400:28)
[36mitem-app_1  |[0m     at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[36mitem-app_1  |[0m     at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m     at Connection.emit (e...
[36mitem-app_1  |[0m     at /app/app.js:24:10
[36mitem-app_1  |[0m     at connectCallback (/app/node_modules/mongodb/lib/mongo_client.js:527:5)
[36mitem-app_1  |[0m     at /app/node_modules/mongodb/lib/mongo_client.js:418:11
[36mitem-app_1  |[0m     at processTicksAndRejections (internal/process/task_queues.js:77:11) {
[36mitem-app_1  |[0m   generatedMessage: true,
[36mitem-app_1  |[0m   code: 'ERR_ASSERTION',
[36mitem-app_1  |[0m   actual: null,
[36mitem-app_1  |[0m   expected: Error [MongoError]: failed to connect to server [item-db:27017] on first connect [Error: connect ECONNREFUSED 172.19.0.2:27017
[36mitem-app_1  |[0m       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) {
[36mitem-app_1  |[0m     name: 'MongoError'
[36mitem-app_1  |[0m   }]
[36mitem-app_1  |[0m       at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:336:35)
[36mitem-app_1  |[0m       at Pool.emit (events.js:400:28)
[36mitem-app_1  |[0m       at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:280:12)
[36mitem-app_1  |[0m       at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m       at Connection.emit (events.js:400:28)
[36mitem-app_1  |[0m       at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:189:49)
[36mitem-app_1  |[0m       at Object.onceWrapper (events.js:520:26)
[36mitem-app_1  |[0m       at Socket.emit (events.js:400:28)
[36mitem-app_1  |[0m       at emitErrorNT (internal/streams/destroy.js:106:8)
[36mitem-app_1  |[0m       at emitErrorCloseNT (internal/streams/destroy.js:74:3),
[36mitem-app_1  |[0m   operator: '=='
[36mitem-app_1  |[0m }
[36mitem-app_1  |[0m npm ERR! code ELIFECYCLE
[36mitem-app_1  |[0m npm ERR! errno 1
[36mitem-app_1  |[0m npm ERR! docker-software-delivery@1.0.0 start: `node ./bin/www`
[36mitem-app_1  |[0m npm ERR! Exit status 1
[36mitem-app_1  |[0m npm ERR! 
[36mitem-app_1  |[0m npm ERR! Failed at the docker-software-delivery@1.0.0 start script.
[36mitem-app_1  |[0m npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
[36mitem-app_1  |[0m 
[36mitem-app_1  |[0m npm ERR! A complete log of this run can be found in:
[36mitem-app_1  |[0m npm ERR!     /root/.npm/_logs/2024-03-20T15_43_23_336Z-debug.log
[33mitem-db_1   |[0m 2024-03-20T15:43:23.453+0000 I STORAGE  [initandlisten] WiredTiger message [1710949403:452937][1:0x7f6fbd22aa40], txn-recover: Main recovery loop: starting at 4/4736
[33mitem-db_1   |[0m 2024-03-20T15:43:23.709+0000 I STORAGE  [initandlisten] WiredTiger message [1710949403:709937][1:0x7f6fbd22aa40], txn-recover: Recovering log 4 through 5
[33mitem-db_1   |[0m 2024-03-20T15:43:23.871+0000 I STORAGE  [initandlisten] WiredTiger message [1710949403:871048][1:0x7f6fbd22aa40], txn-recover: Recovering log 5 through 5
[33mitem-db_1   |[0m 2024-03-20T15:43:24.116+0000 I STORAGE  [initandlisten] WiredTiger message [1710949404:116218][1:0x7f6fbd22aa40], txn-recover: Set global recovery timestamp: 0
[33mitem-db_1   |[0m 2024-03-20T15:43:24.317+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2024-03-20T15:43:24.317+0000 I CONTROL  [initandlisten] ** WARNING: Access control is not enabled for the database.
[33mitem-db_1   |[0m 2024-03-20T15:43:24.317+0000 I CONTROL  [initandlisten] **          Read and write access to data and configuration is unrestricted.
[33mitem-db_1   |[0m 2024-03-20T15:43:24.317+0000 I CONTROL  [initandlisten] 
[33mitem-db_1   |[0m 2024-03-20T15:43:24.383+0000 I FTDC     [initandlisten] Initializing full-time diagnostic data capture with directory '/data/db/diagnostic.data'
[33mitem-db_1   |[0m 2024-03-20T15:43:24.394+0000 I NETWORK  [initandlisten] listening via socket bound to 0.0.0.0
[33mitem-db_1   |[0m 2024-03-20T15:43:24.414+0000 I NETWORK  [initandlisten] listening via socket bound to /tmp/mongodb-27017.sock
[33mitem-db_1   |[0m 2024-03-20T15:43:24.414+0000 I NETWORK  [initandlisten] waiting for connections on port 27017
[32mitem-app_1  |[0m 
[32mitem-app_1  |[0m > docker-software-delivery@1.0.0 start /app
[32mitem-app_1  |[0m > node ./bin/www
[32mitem-app_1  |[0m 
[32mitem-app_1  |[0m NODE_ENV: production
[33mitem-db_1   |[0m 2024-03-20T15:43:25.838+0000 I NETWORK  [listener] connection accepted from 172.19.0.3:49070 #1 (1 connection now open)
[33mitem-db_1   |[0m 2024-03-20T15:43:25.847+0000 I NETWORK  [conn1] received client metadata from 172.19.0.3:49070 conn1: { driver: { name: "nodejs", version: "2.2.36" }, os: { type: "Linux", name: "linux", architecture: "x64", version: "5.4.0-169-generic" }, platform: "Node.js v14.21.3, LE, mongodb-core: 2.1.20" }
[32mitem-app_1  |[0m Connected to database
Gracefully stopping... (press Ctrl+C again to force)
